id = "mint-theme"
name = "Mint base theme for zed"
description = "Mint base theme for zed IDE"
version = "0.1.0"
schema_version = 1
authors = ["Ivanopulo124 <ivanopulo1628@gmail.com>"]
repository = "https://github.com/Ivanopulo124/zed-theme-mint"
